### ISSUE TITLE
Description field

### ISSUE THREAD

**Issue by JLRishe** [SteelsenS/ASpace_Questions#14]
[The mockup](https://github.com/SteelsenS/ASpace_Questions/files/1582825/DEV_.ICE_mockup_10.17.2017.docx) that @andreamccarty sent me in October contains a field called "Description" under the Collection Information section, but I'm not sure whether or not this field is mentioned in [@SteelsenS's Gist](https://gist.github.com/SteelsenS/530220a88e2cbfabefae394737c73d2e). Is this the same as the (4) Display Title field? Or something else?

**Comment by kevinglick** [comment]
Yes, I think this is the same.

Kevin L. Glick
Sent from my phone
---------------------------------

On Dec 22, 2017, at 10:17 AM, Jimmy Rishe <notifications@github.com<mailto:notifications@github.com>> wrote:


The mockup<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_SteelsenS_ASpace-5FQuestions_files_1582825_DEV-5F.ICE-5Fmockup-5F10.17.2017.docx&d=DwMCaQ&c=cjytLXgP8ixuoHflwc-poQ&r=CK9e0KaBmaKGQ2OA05tW1wK_R6XFg9f4MbIJwdE2L-E&m=88LEu9vgnYLZM9r0F1UGq6GyTWJR7XZX9epTUwK7jGY&s=c6JnVi79M_DVZG_-uN7YdpUsUTSMomIj0TBYG4jSX3Q&e=> that @andreamccarty<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_andreamccarty&d=DwMCaQ&c=cjytLXgP8ixuoHflwc-poQ&r=CK9e0KaBmaKGQ2OA05tW1wK_R6XFg9f4MbIJwdE2L-E&m=88LEu9vgnYLZM9r0F1UGq6GyTWJR7XZX9epTUwK7jGY&s=KDQDUZB1GF4SQjerDKG1k1OnRl_qsiFxg5mFitviuVk&e=> sent me in October contains a field called "Description" under the Collection Information section, but I'm not sure whether or not this field is mentioned in @SteelsenS's Gist<https://urldefense.proofpoint.com/v2/url?u=https-3A__gist.github.com_SteelsenS_530220a88e2cbfabefae394737c73d2e&d=DwMCaQ&c=cjytLXgP8ixuoHflwc-poQ&r=CK9e0KaBmaKGQ2OA05tW1wK_R6XFg9f4MbIJwdE2L-E&m=88LEu9vgnYLZM9r0F1UGq6GyTWJR7XZX9epTUwK7jGY&s=SKiU_qF8hs1AJVCJ7y_gaK7BibYkXMO6H5bbnBZ_z1M&e=>. Is this the same as the (4) Display Title field? Or something else?

**Comment by andreamccarty** [comment]
You can completely disregard the “Description” field under the Collection Info section from the October mockup. At one point, we had envisioned Collections Description information there, but realized soon after that it was not feasible. As of right now, there are only three fields under Collection Info: Collection Name, Collection Date and Call #.
